# Generated by Django 4.2.22 on 2025-08-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("company", "0010_companyprofile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/resumes/"
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("offered", "Offered"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidate.profile",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="company.companyprofile",
                    ),
                ),
                (
                    "internship_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="company.internshippost",
                    ),
                ),
                (
                    "job_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="company.jobpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("job_post__isnull", False), ("internship_post__isnull", True)
                    ),
                    models.Q(
                        ("job_post__isnull", True), ("internship_post__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="applications_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_post__isnull", False)),
                fields=("candidate", "job_post"),
                name="unique_candidate_job_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internship_post__isnull", False)),
                fields=("candidate", "internship_post"),
                name="unique_candidate_internship_application",
            ),
        ),
    ]
