# Generated by Django 4.2.22 on 2025-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="unique_candidate_job_application",
        ),
        migrations.RemoveConstraint(
            model_name="application",
            name="unique_candidate_internship_application",
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("job_post__isnull", False),
                    models.Q(("status__in", ["withdrawn", "rejected"]), _negated=True),
                ),
                fields=("candidate", "job_post"),
                name="uniq_active_job_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("internship_post__isnull", False),
                    models.Q(("status__in", ["withdrawn", "rejected"]), _negated=True),
                ),
                fields=("candidate", "internship_post"),
                name="uniq_active_intern_application",
            ),
        ),
    ]
