# Generated by Django 4.2.22 on 2026-07-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_feedback'),
        ('company', '0012_companyprofile_credits_balance'),
        ('applications', '0002_remove_application_unique_candidate_job_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('offered_salary', models.CharField(help_text='e.g. NPR 45,000 / month or Paid Internship NPR 15,000/month', max_length=150)),
                ('joining_date', models.DateField()),
                ('work_location', models.CharField(default='On-site', max_length=150)),
                ('employment_type', models.CharField(default='Full Time', max_length=100)),
                ('expiration_date', models.DateField(help_text='Last date for candidate to accept the offer')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Specific job duties, working hours, probation period, etc.')),
                ('hr_name', models.CharField(max_length=150, verbose_name='HR / Hiring Manager Name')),
                ('hr_designation', models.CharField(default='Hiring Manager', max_length=150, verbose_name='HR Designation')),
                ('hr_signature', models.ImageField(blank=True, help_text='Uploaded digital signature image', null=True, upload_to='offer_letters/signatures/')),
                ('status', models.CharField(choices=[('pending', 'Pending Candidate Acceptance'), ('accepted', 'Accepted by Candidate'), ('declined', 'Declined by Candidate'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('candidate_response_notes', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to='candidate.profile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_offers', to='company.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
