# Generated by Django 4.2.22 on 2026-09-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_bookmark'),
        ('company', '0013_jobpost_slug'),
        ('applications', '0003_alter_application_status_offerletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(default='Technical Interview', max_length=150)),
                ('interview_type', models.CharField(choices=[('video', 'Online Video Call'), ('in_person', 'In-Person'), ('phone', 'Phone Screening')], default='video', max_length=50)),
                ('scheduled_at', models.DateTimeField(help_text='Scheduled date and time of the interview')),
                ('duration_minutes', models.PositiveIntegerField(default=45, help_text='Duration in minutes')),
                ('meeting_link', models.CharField(blank=True, help_text='Meeting URL (Google Meet, Zoom, MS Teams) or physical location address', max_length=500)),
                ('interviewer_name', models.CharField(blank=True, help_text='Name of the interviewer or panel', max_length=150)),
                ('instructions', models.TextField(blank=True, help_text='Preparation notes, topics, or agenda for the candidate')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed by Candidate'), ('reschedule_requested', 'Reschedule Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('candidate_notes', models.TextField(blank=True, help_text='Notes/reason provided by candidate on RSVP or reschedule', null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidate.profile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to='company.companyprofile')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
