# Generated by Django 4.2.22 on 2025-09-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0012_companyprofile_credits_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("credits_qty", models.IntegerField()),
                ("unit_price_paisa", models.IntegerField()),
                ("discount_percent", models.IntegerField(default=0)),
                ("vat_percent", models.IntegerField(default=13)),
                ("subtotal_paisa", models.IntegerField()),
                ("total_paisa", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("KHALTI", "Khalti"),
                            ("ESEWA", "eSewa"),
                            ("BANK", "Bank Transfer"),
                            ("QR", "QR Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="company.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("GRANT", "Grant"),
                            ("DEBIT", "Debit"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                ("credits_delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("consumed_batches", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="company.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("KHALTI", "Khalti"),
                            ("ESEWA", "eSewa"),
                            ("BANK", "Bank Transfer"),
                            ("QR", "QR Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="INITIATED",
                        max_length=12,
                    ),
                ),
                ("requested_amount_paisa", models.IntegerField()),
                ("verified_amount_paisa", models.IntegerField(blank=True, null=True)),
                (
                    "provider_ref",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "provider_txn_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="membership.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_credits", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="company.companyprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SIGNUP_BONUS", "Signup Bonus"),
                            ("TOPUP", "Top-up"),
                            ("PLAN", "Plan"),
                            ("ADJUSTMENT", "Admin Adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("credits_total", models.IntegerField()),
                ("credits_remaining", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_batches",
                        to="company.companyprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "expires_at"],
                        name="membership__company_5e9e49_idx",
                    )
                ],
            },
        ),
    ]
