# Generated by Django 4.2.22 on 2025-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider_ref",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
