# Generated by Django 4.2.22 on 2026-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_payment_provider_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING_VERIFICATION', 'Pending Verification'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', max_length=24),
        ),
    ]
