# Generated by Django 4.2.22 on 2025-07-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("company", "Company"), ("candidate", "Candidate")],
                max_length=10,
            ),
        ),
    ]
