# Generated by Django 4.2.22 on 2025-07-24 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                ("industry", models.CharField(max_length=100)),
                ("founded_date", models.DateField()),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1–10 employees"),
                            ("11-50", "11–50 employees"),
                            ("51-200", "51–200 employees"),
                            ("201-500", "201–500 employees"),
                            ("501-1000", "501–1000 employees"),
                            ("1001+", "1001+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("about_company", models.TextField()),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "website_url",
                    models.URLField(blank=True, null=True, verbose_name="Website URL"),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Koshi", "Koshi (Province No.1)"),
                            ("Madhesh", "Madhesh (Province No.2)"),
                            ("Bagmati", "Bagmati (Province No.3)"),
                            ("Gandaki", "Gandaki (Province No.4)"),
                            ("Lumbini", "Lumbini (Province No.5)"),
                            ("Karnali", "Karnali (Province No.6)"),
                            ("Sudurpashchim", "Sudurpashchim (Province No.7)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("postal_code", models.CharField(max_length=20)),
                ("current_address", models.CharField(max_length=255)),
                (
                    "social_link",
                    models.URLField(blank=True, null=True, verbose_name="Social Link"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
    ]
