# Generated by Django 4.2.22 on 2025-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a square PNG/JPG up to 2-MB",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
