# Generated by Django 4.2.22 on 2025-07-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_companyprofile_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InternshipPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Onsite", "Onsite"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("Web Development", "Web Development"),
                            ("UI/UX", "UI/UX"),
                            ("Marketing", "Marketing"),
                            ("Data Science", "Data Science"),
                        ],
                        max_length=50,
                    ),
                ),
                ("application_deadline", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full‑Time", "Full‑Time"),
                            ("Part‑Time", "Part‑Time"),
                            ("Contract", "Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Entry", "Entry"),
                            ("Mid", "Mid"),
                            ("Senior", "Senior"),
                        ],
                        max_length=20,
                    ),
                ),
                ("openings", models.PositiveIntegerField()),
                ("comp_min", models.PositiveIntegerField(verbose_name="Min Salary")),
                ("comp_max", models.PositiveIntegerField(verbose_name="Max Salary")),
                (
                    "comp_frequency",
                    models.CharField(
                        choices=[
                            ("Hourly", "Hourly"),
                            ("Daily", "Daily"),
                            ("Monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("responsibilities", models.TextField(blank=True)),
                ("qualifications", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="company.companyprofile",
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="company.skill")),
            ],
        ),
    ]
