# Generated by Django 4.2.22 on 2025-07-24 09:15

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("company", "0003_skill_internshippost"),
    ]

    operations = [
        # 1) drop the old M2M column & join table
        migrations.RemoveField(
            model_name="internshippost",
            name="skills",
        ),
        # 2) drop the Skill model entirely
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
