# Generated by Django 4.2.22 on 2025-07-24 09:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("company", "0004_delete_skill_alter_internshippost_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshippost",
            name="skills",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
