# Generated by Django 4.2.22 on 2025-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_internshippost_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshippost",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
