# Generated by Django 4.2.22 on 2025-07-24 16:53

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("company", "0007_internshippost_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Koshi", "Koshi (Province No.1)"),
                            ("Madhesh", "Madhesh (Province No.2)"),
                            ("Bagmati", "Bagmati (Province No.3)"),
                            ("Gandaki", "Gandaki (Province No.4)"),
                            ("Lumbini", "Lumbini (Province No.5)"),
                            ("Karnali", "Karnali (Province No.6)"),
                            ("Sudurpashchim", "Sudurpashchim (Province No.7)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("Onsite", "Onsite"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Design", "Design"),
                            ("Data", "Data"),
                            ("Healthcare", "Healthcare"),
                            ("Education", "Education"),
                        ],
                        max_length=50,
                    ),
                ),
                ("application_deadline", models.DateField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Internship", "Internship"),
                            ("Contract", "Contract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        choices=[
                            ("Entry", "Entry"),
                            ("Mid", "Mid"),
                            ("Senior", "Senior"),
                            ("Lead", "Lead"),
                        ],
                        max_length=20,
                    ),
                ),
                ("experience_required", models.PositiveIntegerField()),
                (
                    "experience_unit",
                    models.CharField(
                        choices=[("Years", "Years"), ("Months", "Months")],
                        max_length=10,
                    ),
                ),
                ("openings", models.PositiveIntegerField()),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("responsibilities", models.TextField(blank=True)),
                ("qualifications", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to="company.companyprofile",
                    ),
                ),
                (
                    "skills",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
