# Generated by Django 4.2.22 on 2025-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_jobpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="notify_all",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="notify_on_application",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="notify_on_message",
            field=models.BooleanField(default=True),
        ),
    ]
