# Generated by Django 4.2.22 on 2025-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_companyprofile_notify_all_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active?"),
        ),
    ]
