# Generated by Django 4.2.22 on 2025-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_companyprofile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.AlterField(
            model_name="internshippost",
            name="sector",
            field=models.CharField(
                help_text="Select from admin-managed sectors", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="internshippost",
            name="type",
            field=models.CharField(
                choices=[
                    ("Full-Time", "Full-Time"),
                    ("Part-Time", "Part-Time"),
                    ("Contract", "Contract"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="sector",
            field=models.CharField(
                help_text="Select from admin-managed sectors", max_length=50
            ),
        ),
    ]
