# Generated by Django 4.2.22 on 2025-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_sector_alter_internshippost_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="credits_balance",
            field=models.PositiveIntegerField(
                default=50, help_text="Prepaid credits for job posting"
            ),
        ),
    ]
