SKILL_SYNONYMS = {          # small normalizer for skills
    "js": "javascript", "reactjs": "react", "react.js": "react", "node": "nodejs",
    "drf": "django rest framework", "ps": "photoshop", "photoshop cc": "photoshop",
    "ai": "artificial intelligence", "ml": "machine learning", "nlp": "natural language processing",
    "excel": "ms excel", "word": "ms word", "powerpoint": "ms powerpoint",
    "figma": "figma design", "uiux": "ui/ux",  "ui/ux design": "ui/ux", "ui": "ui/ux", "ux": "ui/ux",
    "c#": "csharp", "c++": "cpp", "py": "python", "ts": "typescript",   "html": "html5", "css": "css3",
    "rest": "rest api", "restful": "rest api", "rest apis": "rest api",
    "aws": "amazon web services", "gcp": "google cloud", "google cloud platform": "google cloud",
    "docker": "docker containerization", "k8s": "kubernetes", "kubernetes": "kubernetes", 
    "ci/cd": "ci cd", "ci cd": "ci cd", "continuous integration": "ci cd", "continuous delivery": "ci cd", 
    "agile": "agile methodologies", "scrum": "agile methodologies", "kanban": "agile methodologies",
    "seo": "search engine optimization", "sem": "search engine marketing",
    "ppc": "pay per click", "smm": "social media marketing",
    "saas": "saas products", "saas product": "saas products",
    "b2b": "b2b sales", "b2c": "b2c sales",
    "erp": "erp systems", "crm": "crm systems",
    "hr": "hr management", "hrms": "hr management",
    "fullstack": "full stack", "full-stack": "full stack",
    "front-end": "frontend", "front end": "frontend", "frontend": "frontend",
    "back-end": "backend", "back end": "backend", "backend": "backend",
    "data science": "data scientist", "datascience": "data scientist", "data scientist": "data scientist",
    "data analyst": "data analyst", "data analytics": "data analyst",
    "data engineering": "data engineer", "data engineer": "data engineer",
    "devops": "devops engineer", "devops engineer": "devops engineer",
    "ui designer": "ui/ux", "ux designer": "ui/ux",
    "graphic designer": "graphic design", "graphic design": "graphic design",
    "digital marketing": "digital marketing", "digital marketer": "digital marketing", 
    
}