# Skill normalization and taxonomy dictionary

SKILL_SYNONYMS = {
    # Web & Languages
    "js": "javascript",
    "ts": "typescript",
    "py": "python",
    "c#": "csharp",
    "c++": "cpp",
    "golang": "go",
    "rb": "ruby",
    "html": "html5",
    "css": "css3",
    "scss": "sass",
    "sass": "sass",
    "tailwind": "tailwindcss",
    "tailwind css": "tailwindcss",
    "bs": "bootstrap",
    "bootstrap 5": "bootstrap",
    "reactjs": "react",
    "react.js": "react",
    "react native": "react native",
    "nextjs": "next.js",
    "next": "next.js",
    "vuejs": "vue",
    "vue.js": "vue",
    "angularjs": "angular",
    "node": "nodejs",
    "node.js": "nodejs",
    "expressjs": "express",
    "express.js": "express",
    "drf": "django rest framework",
    "fast api": "fastapi",
    "springboot": "spring boot",
    "spring": "spring boot",
    "ror": "ruby on rails",
    "rails": "ruby on rails",
    ".net": "dotnet",
    "asp.net": "dotnet",

    # Mobile
    "flutter": "flutter",
    "dart": "dart",
    "kotlin": "kotlin",
    "swift": "swift",
    "android development": "android",
    "ios development": "ios",

    # Databases & Cloud
    "postgres": "postgresql",
    "psql": "postgresql",
    "mongo": "mongodb",
    "ms sql": "sql server",
    "mssql": "sql server",
    "mysql": "mysql",
    "redis": "redis",
    "aws": "amazon web services",
    "amazon web services": "aws",
    "gcp": "google cloud",
    "google cloud platform": "google cloud",
    "azure": "microsoft azure",
    "k8s": "kubernetes",
    "docker": "docker",
    "docker containerization": "docker",
    "ci/cd": "ci cd",
    "continuous integration": "ci cd",
    "continuous delivery": "ci cd",

    # Data & AI
    "ai": "artificial intelligence",
    "ml": "machine learning",
    "dl": "deep learning",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "data science": "data scientist",
    "datascience": "data scientist",
    "data analytics": "data analyst",
    "data analysis": "data analyst",
    "data engineering": "data engineer",
    "devops": "devops engineer",
    "pandas": "pandas",
    "numpy": "numpy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
    "tf": "tensorflow",

    # Design & Tools
    "ps": "photoshop",
    "photoshop cc": "photoshop",
    "figma": "figma",
    "figma design": "figma",
    "uiux": "ui/ux",
    "ui/ux design": "ui/ux",
    "ui": "ui/ux",
    "ux": "ui/ux",
    "ui designer": "ui/ux",
    "ux designer": "ui/ux",
    "graphic designer": "graphic design",
    "git": "git",
    "github": "github",
    "gitlab": "gitlab",
    "jira": "jira",
    "agile": "agile",
    "scrum": "agile",
    "kanban": "agile",
    "rest": "rest api",
    "restful": "rest api",
    "rest apis": "rest api",
    "graphql": "graphql",

    # Business & Marketing
    "seo": "search engine optimization",
    "sem": "search engine marketing",
    "ppc": "pay per click",
    "smm": "social media marketing",
    "digital marketer": "digital marketing",
    "digital marketing": "digital marketing",
    "saas": "saas",
    "b2b": "b2b sales",
    "b2c": "b2c sales",
    "hr": "hr management",
    "hrms": "hr management",
    "excel": "ms excel",
    "word": "ms word",
    "powerpoint": "ms powerpoint",

    # Roles
    "fullstack": "full stack",
    "full-stack": "full stack",
    "front-end": "frontend",
    "front end": "frontend",
    "back-end": "backend",
    "back end": "backend",
}

# Skill clusters / parent relationships for soft matching (gives partial credit if related)
SKILL_RELATIONS = {
    # Frameworks -> Parent languages / foundational skills
    "django": {"python", "backend", "web development", "sql"},
    "django rest framework": {"django", "python", "rest api", "backend"},
    "fastapi": {"python", "backend", "rest api"},
    "flask": {"python", "backend", "rest api"},
    "react": {"javascript", "frontend", "web development"},
    "next.js": {"react", "javascript", "typescript", "frontend", "web development"},
    "vue": {"javascript", "frontend", "web development"},
    "angular": {"typescript", "javascript", "frontend", "web development"},
    "nodejs": {"javascript", "backend", "web development"},
    "express": {"nodejs", "javascript", "backend", "rest api"},
    "spring boot": {"java", "backend", "rest api"},
    "flutter": {"dart", "mobile", "cross-platform"},
    "react native": {"react", "javascript", "mobile", "cross-platform"},
    "tailwindcss": {"css3", "frontend"},
    "bootstrap": {"css3", "frontend"},
    "postgresql": {"sql", "database", "backend"},
    "mysql": {"sql", "database", "backend"},
    "sql server": {"sql", "database", "backend"},
    "mongodb": {"nosql", "database", "backend"},
    "pandas": {"python", "data analyst", "data scientist"},
    "numpy": {"python", "data scientist"},
    "scikit-learn": {"python", "machine learning", "data scientist"},
    "tensorflow": {"python", "deep learning", "machine learning"},
    "pytorch": {"python", "deep learning", "machine learning"},
    "docker": {"devops", "containerization"},
    "kubernetes": {"docker", "devops", "cloud"},
    "aws": {"cloud", "devops"},
    "google cloud": {"cloud", "devops"},
}